<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging.Configuration" Version="10.0.8" />
    <PackageReference Include="Selenium.Chrome.WebDriver" Version="85.0.0" />
    <PackageReference Include="Selenium.Support" Version="4.44.0" />
    <PackageReference Include="Selenium.WebDriver" Version="4.44.0" />
    <PackageReference Include="Selenium.WebDriver.ChromeDriver" Version="148.0.7778.17800" />
    <PackageReference Include="SeleniumExtras.WaitHelpers" Version="1.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Base\Base.csproj" />
  </ItemGroup>

</Project>
