name: .NET Module 10 CI/CD

on:
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 19 * * *'
  workflow_dispatch: 
   inputs:
    browser:
      description: Browser for UI tests
      required: true
      default: chrome
      type: choice
      options:
        - chrome
        - edge

jobs:
  api-tests:
    name: API Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Verify Chrome
        run: |
          google-chrome --version

      - name: Install Edge
        run: |
          curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
          sudo install -o root -g root -m 644 microsoft.gpg /etc/apt/trusted.gpg.d/
          sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/edge stable main" > /etc/apt/sources.list.d/microsoft-edge.list'
          sudo apt-get update
          sudo apt-get install -y microsoft-edge-stable

      - name: Restore
        run: dotnet restore

      - name: Run API tests
        run: |
          mkdir -p TestResults/API
          dotnet test \
            --filter "Category=API" \
            --results-directory TestResults/API \
            --logger "trx;LogFileName=api.trx"

      - name: Upload API test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: api-test-results
          path: TestResults/API

  ui-tests:
    name: UI Tests
    runs-on: ubuntu-latest
    needs: api-tests
    # ensure UI job runs even if API job failed
    if: always()
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Verify Chrome
        run: |
          google-chrome --version

      - name: Install Edge
        run: |
          curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
          sudo install -o root -g root -m 644 microsoft.gpg /etc/apt/trusted.gpg.d/
          sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/edge stable main" > /etc/apt/sources.list.d/microsoft-edge.list'
          sudo apt-get update
          sudo apt-get install -y microsoft-edge-stable

      - name: Restore
        run: dotnet restore

      - name: Run UI tests
        run: |
          mkdir -p TestResults/UI
          dotnet test \
            --filter "Category=UI" \
            --results-directory TestResults/UI \
            --logger "trx;LogFileName=ui.trx"

      - name: Upload UI test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ui-test-results
          path: TestResults/UI

